# Generated by Django 6.1.1 on 2026-09-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('unvan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ünvan')),
                ('url_slug', models.SlugField(unique=True, verbose_name='URL Uzantısı (Örn: ali-kadir)')),
                ('profil_fotografi', models.ImageField(upload_to='profiller/', verbose_name='Profil Fotoğrafı')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('google_maps', models.URLField(blank=True, null=True, verbose_name='Google Maps')),
                ('iban', models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN')),
            ],
        ),
    ]
