# Generated by Django 6.1.1 on 2026-09-03 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartvizit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musteri',
            name='email',
        ),
        migrations.RemoveField(
            model_name='musteri',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='musteri',
            name='google_maps',
        ),
        migrations.RemoveField(
            model_name='musteri',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='musteri',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='musteri',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='musteri',
            name='whatsapp',
        ),
        migrations.CreateModel(
            name='MusteriLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('telefon', 'Telefon'), ('whatsapp', 'WhatsApp'), ('email', 'E-Posta'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google_maps', 'Google Maps'), ('iban', 'IBAN')], max_length=20, verbose_name='Alan Türü')),
                ('deger', models.CharField(max_length=255, verbose_name='Değer / Numara / Link')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkler', to='kartvizit.musteri')),
            ],
        ),
    ]
