# Generated by Django 6.1.1 on 2026-09-03 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartvizit', '0002_remove_musteri_email_remove_musteri_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta Adresi')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailler', to='kartvizit.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='MusteriFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Profil Linki')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebooklar', to='kartvizit.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='MusteriGoogleMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_maps', models.URLField(blank=True, null=True, verbose_name='Google Maps Konum Linki')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haritalar', to='kartvizit.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='MusteriIban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN Numarası')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibanlar', to='kartvizit.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='MusteriInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Profil Linki')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagramlar', to='kartvizit.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='MusteriTelefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonlar', to='kartvizit.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='MusteriWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Numarası')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapplar', to='kartvizit.musteri')),
            ],
        ),
        migrations.DeleteModel(
            name='MusteriLink',
        ),
    ]
