# Generated by Django 6.1.1 on 2026-09-04 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartvizit', '0003_musteriemail_musterifacebook_musterigooglemaps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musterifacebook',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook Kullanıcı Adı veya Linki'),
        ),
        migrations.AlterField(
            model_name='musterigooglemaps',
            name='google_maps',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Google Maps Konum Linki'),
        ),
        migrations.AlterField(
            model_name='musteriinstagram',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram Kullanıcı Adı veya Linki'),
        ),
        migrations.CreateModel(
            name='MusteriKampanya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kampanya / Duyuru Metni')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kampanyalar', to='kartvizit.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='MusteriSahibinden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sahibinden', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sahibinden Mağaza/Profil Linki veya Kullanıcı Adı')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sahibindenler', to='kartvizit.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='MusteriSnapchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapchat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Snapchat Kullanıcı Adı veya Linki')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapchatler', to='kartvizit.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='MusteriTikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok', models.CharField(blank=True, max_length=255, null=True, verbose_name='TikTok Kullanıcı Adı veya Linki')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktoklar', to='kartvizit.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='MusteriWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Web Sitesi Linki')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websiteler', to='kartvizit.musteri')),
            ],
        ),
    ]
