# Generated by Django 6.1.1 on 2026-09-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartvizit', '0004_alter_musterifacebook_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteriemail',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel İsim'),
        ),
        migrations.AddField(
            model_name='musterifacebook',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel İsim'),
        ),
        migrations.AddField(
            model_name='musterigooglemaps',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel İsim'),
        ),
        migrations.AddField(
            model_name='musteriiban',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banka veya İsim'),
        ),
        migrations.AddField(
            model_name='musteriinstagram',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel İsim'),
        ),
        migrations.AddField(
            model_name='musterikampanya',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel İsim'),
        ),
        migrations.AddField(
            model_name='musterisahibinden',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel İsim'),
        ),
        migrations.AddField(
            model_name='musterisnapchat',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel İsim'),
        ),
        migrations.AddField(
            model_name='musteritelefon',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel İsim'),
        ),
        migrations.AddField(
            model_name='musteritiktok',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel İsim'),
        ),
        migrations.AddField(
            model_name='musteriwebsite',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel İsim'),
        ),
        migrations.AddField(
            model_name='musteriwhatsapp',
            name='isim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel İsim'),
        ),
    ]
