# Generated by Django 6.1.1 on 2026-09-15 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartvizit', '0005_musteriemail_isim_musterifacebook_isim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriLinkedln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedln', models.CharField(blank=True, max_length=255, null=True, verbose_name='Linkedln Kullanıcı Adı veya Linki')),
                ('isim', models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel İsim')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedlnler', to='kartvizit.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='MusteriMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_gorseli', models.ImageField(upload_to='menuler/', verbose_name='Menü Görseli')),
                ('isim', models.CharField(default='Menü İçin Basınız', max_length=50, verbose_name='Buton Yazısı (Örn: Menü İçin Basınız)')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuler', to='kartvizit.musteri')),
            ],
        ),
    ]
